### ISSUE TITLE
I fixed the code as it wasnt working...

### ISSUE THREAD

**Issue by jamieduk** [TomPrograms/Python-Voice-Chat#1]
https://app.box.com/s/488ue975j77k4l2423glha7pr0c0rzq2

also the setup you will need to do the following:

To setup:

sudo apt install -y portaudio19-dev
sudo apt install -y pyaudio
pip install -r requirements.txt

**Comment by el-pr0f3ss0r** [comment]
tysm @jamieduk

**Comment by TomPrograms** [comment]
Sorry guys. I should've seen this months ago, but I haven't been very active on Github.

I see in your code (Jamie) you removed all the spaces in between variables and what is being assigned to the variables. Is this necessary for the code to run on Linux or just a stylistic issue. I take the main issue is just the file headings and a different way of setting up the code w/ installs and such? Let me know and I'll merge the pull request @el-pr0f3ss0r made after I clean it up a little (if that is okay with you @jamieduk, as I believe he included your adaptations).

**Comment by TomPrograms** [comment]
Thanks @jamieduk for the contributions. I'll take what you put here and integrate it into the main repository.

**Comment by TomPrograms** [comment]
I fixed the repository by adding the shebangs and adding the extra installation advice to the Readme.md. Thanks Jamie.
