### ISSUE TITLE
Long time running, the delay is obvious

### ISSUE THREAD

**Issue by yuqizhi** [TomPrograms/Python-Voice-Chat#4]
When I run for a long time, the sound delay will get longer and longer ,How can i solve this problem ?

**Comment by TomPrograms** [comment]
I'm not actually sure sorry. I'm presuming this is a problem with your machine rather than with the code, and I'm not sure how you would fix it. Sorry.

**Comment by yuqizhi** [comment]
I suggest you use UDP
