### ISSUE TITLE
Web Server Implementation

### ISSUE THREAD

**Issue by ElliottStorey** [TomPrograms/Python-Voice-Chat#8]
Hello! The program works great and I am able to connect with no problem. Any ideas of how I could implement this program into a webserver? For example, I would run server.py on a webserver and have two clients connect via a website to talk. Do you know of a way I could do this using flask, heroku, or replit? Thank you!

**Comment by TomPrograms** [comment]
I don't believe this program would work with the web as it uses direct networking. As far as I'm aware you'd have to build something from the ground up using Javascript, maybe using WebRTC. This looks like a much more relevant project: https://github.com/peer-calls/peer-calls

**Comment by ElliottStorey** [comment]
Thank you! I have actually started on a video chat using those methods, so check out my GitHub soon if you are interested.
